server:
  port: 8088

eureka:
  client:
    registerWithEureka: false   
    fetchRegistry: false
  server:
    waitTimeInMsWhenSyncEmpty: 0

mybatis:
  typeAliasesPackage: com.chanhong.DIPSMarketPerspectiveService.entity
  mapperLocations: classpath:mapper/*.xml
  configuration:
      conf-iglocation: classpath:/mybatis/mybatis-config.xml
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
      mapUnderscoreToCamelCase: true
    
spring:  
  application:
        name: MyEamil
  #访问数据库的配置
  datasource:
      url: jdbc:mysql://144.34.227.161:3306/zzc?useSSL=false&useUnicode=true&amp;characterEncoding=utf-8
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
  #服务发送邮件配置
  mail:
    host: smtp.qq.com
    username: 2446522301@qq.com
    password: vuuzoiojvjhidjac
    properties:
            smtp:
              auth: true
              starttls:
                  enable: true
                  required: true
  thymeleaf:
       cache: false
       mode: LEGACYHTML5
       
       